###############################################################################################################
#                                                                                                             #
#                                      Armstrong (aka. LunarUtility)                                          #
#                                                                                                             #
#                                          Maintained by Vaption                                              #
#                                  (Originally made by RefineDevelopment)                                     #
#                                                                                                             #
###############################################################################################################

###############################################################################################################
#                                                                                                             #
#   Set this to true if you want to force LunarClient on your server.                                         #
#   People joining with anything else will be kicked from the server.                                         #
#   The kick message can be configured below. <space> adds a new line.                                        #
#                                                                                                             #
#   Color codes are supported (See https://wiki.ess3.net/mc/).                                                #
#                                                                                                             #
###############################################################################################################

REQUIRE-LUNAR:
  ENABLED: false
  MESSAGE: "&cLunar Client is required to play on the server! <space> &cDownload at &olunarclient.com/download"

###############################################################################################################
#                                                                                                             #
#  In Armstrong, the Nametag module supports a permission-based system (tiers):                               #
#      - You can customize the nametag format based on permissions assigned to players.                       #
#      - Assuming the player has multiple matching permissions, the highest weight has the highest priority.  #
#                                                                                                             #
#  Notes:                                                                                                     #
#     - Armstrong supports PlaceholderAPI placeholders in nametag formats (if PAPI is installed).             #
#     - Additionally, you can use <player_name>, <player_displayname>, and <status> placeholders.             #
#     - You can leave the permission value empty if you want it to apply to all players.                      #
#     - If none of the defined tiers match, the nametag module skips that line for the player.                #
#     - Armstrong implements four Apollo nametag lines. Adding more manually does not work (for now).         #
#                                                                                                             #
###############################################################################################################

NAMETAG:
  ENABLE: true      # Enable the Armstrong Apollo nametag module implementation
  TICKS: 40         # Update interval in ticks
  FIRST:            # The first line of the nametag
    ENABLE: true
    TIERS:
      staff:
        permission: "armstrong.nametag.staff"
        weight: 100
        format: "&7&o[Staff]"
      status:
        permission: "armstrong.nametag.status"
        weight: 50
        format: "&7[<status> &bLunarClient&7]"
  SECOND:
    ENABLE: true
    TIERS:
      default:
        permission: ""
        weight: 0
        format: "<player_displayname>"
  THIRD:
    ENABLE: false
    TIERS:
      vip:
        permission: "armstrong.nametag.vip"
        weight: 75
        format: "&6[VIP]"
      default:
        permission: ""
        weight: 0
        format: "&7[Player]"
  FOURTH:
    ENABLE: false
    TIERS:
      default:
        permission: ""
        weight: 0
        format: ""

###############################################################################################################
#                                                                                                             #
#  The placeholder text that indicates if user is on/off LunarClient                                          #
#  This is also used in the %lunar_status% PAPI placeholder, as well as <status> in nametags.                 #
#                                                                                                             #
###############################################################################################################

OTHER:
  ENABLED: "&aON&r"
  DISABLED: "&cOFF&r"

###############################################################################################################
#                                                                                                             #
#  Messages in the plugin. Can be configured to your liking.                                                  #
#                                                                                                             #
###############################################################################################################

MESSAGES:
  MAIN:
    RELOAD: "&6Armstrong &ehas been reloaded."
    OFFLINE: "&cThat player doesn't exist."
  LUNAR-COMMAND:
    PLAYER: "&6You are currently <status> &eLunarClient."
    TARGET: "&e<target> &6is currently <status> &eLunarClient."
  LUNAR-STAFF-COMMAND:
    ENABLE:
     PLAYER: "&aYou have enabled all LunarClient staff mods."
     TARGET: "&aYou have enabled all LunarClient staff mods for <target>."
     TO-TARGET: "&aAll LunarClient staff mods have been enabled for you by <player>."
     ERROR: "&cPlayer <player> is not on LunarClient."
    DISABLE:
      PLAYER: "&cYou have disabled your LunarClient staff mods."
      TARGET: "&6You have disabled &e<target>'s &6LunarClient staff mods."
      TO-TARGET: "&cYour LunarClient staff mods have been disabled by <player>."
  LUNAR-USERS-COMMAND:
    SEPERATOR: "&7, "
    MESSAGE:
      - "&7&m-----------------------"
      - "&b&lLunarClient Users &7[<totalUsers>]"
      - "<playerList>"
      - "&7&m-----------------------"